### ISSUE TITLE
test_time for DLA-34

### ISSUE THREAD

**Issue by SherlockHolmes221** [YueLiao/PPDM#19] opened 2020-07-26 01:34 UTC
I test the DLAbackbone but get the test time about 480ms per image(But the paper said 27ms)

![e6633c6d958e3aca1a2c025f761472d](https://user-images.githubusercontent.com/28208801/88469296-ac9c8d00-cf22-11ea-95e4-cf74dc62a48f.png)

**Comment by YueLiao** [comment] 2020-07-26 01:39
Can you provide more details about the environments？

**Comment by SherlockHolmes221** [comment] 2020-07-26 01:48
I set up the environments follow READMD.md

![780e4cb346968554749771a1d360161](https://user-images.githubusercontent.com/28208801/88469526-e1a9df00-cf24-11ea-9f5f-1167258e9644.png)
![181174d2567496df617a704a177e5d1](https://user-images.githubusercontent.com/28208801/88469531-ef5f6480-cf24-11ea-9dce-59ed25198752.png)
![9b92b4781195ee4aea9abef4baba02a](https://user-images.githubusercontent.com/28208801/88469536-fb4b2680-cf24-11ea-97a4-021db81a6154.png)

**Comment by YueLiao** [comment] 2020-07-26 01:59
I will check this problem latter today， and I guess it may be caused by the DCN.

**Comment by YueLiao** [comment] 2020-07-26 11:51
I have checked the code and run the inference again, and it only costs about 18ms for "net inference".  Could you report the inference time of each stage of DLA net? I think it caused by the DCN module.

**Comment by SherlockHolmes221** [comment] 2020-07-26 12:16
I print the time
![adc01e4709474e333f508c65b40524b](https://user-images.githubusercontent.com/28208801/88478680-de424200-cf7c-11ea-8ea6-dfc93ec551dd.png)

**Comment by YueLiao** [comment] 2020-07-26 13:26
I am confused by the following aspects:

-the time4-time1=0.47s, time3-time2=0.02s, time2-time=0.089s, thus time4-time3=0.38s, but the head only consists of 2-layer parallel convolutions.

-About the inference time of dla backbones time3-time1, you can ask help for the [Center](https://github.com/xingyizhou/CenterNet). We use the same backbone as CenterNet, and it reports 52 FPS for a single scale 512-sized image for the object detection task.

**Comment by SherlockHolmes221** [comment] 2020-07-27 00:10
I solve it by update the PyTorch1.0 and DCN.

**Comment by YueLiao** [comment] 2020-07-27 02:42
> I solve it by update the PyTorch1.0 and DCN.

It is strange to me. Before last week, lots of guys have reproduced the speed and performance, but in last and this weak, you and someone else have proposed the problem of the inference time of DLA-34.

**Comment by SherlockHolmes221** [comment] 2020-07-27 03:13
Training also becomes faster when update to 1.0 but not sure the performance will be as well as 0.4

**Comment by YueLiao** [comment] 2020-07-27 03:21
> Training also becomes faster when update to 1.0 but not sure the performance will be as well as 0.4

Thx for your advice. I will try to update the code to pt1.4 or pt1.5 with DistributedDataParrell (DDP) and equip it with apex (fp16 or SyncBN) to accelerate it, if I have spare time.

**Comment by SherlockHolmes221** [comment] 2020-07-27 03:23
Thanks and closing it

**Comment by SherlockHolmes221** [comment] 2020-07-27 09:19
37fps is get by just the net time or total time?

**Comment by YueLiao** [comment] 2020-07-27 09:20
Total time in Titan Xp.

**Comment by SherlockHolmes221** [comment] 2020-07-27 09:44
I get **net 29ms**, may be still something wrong in DLA

**Comment by YueLiao** [comment] 2020-08-06 08:38
Close it. And feel free to reopen, if any problems.

**Closed by YueLiao** 2020-08-06 08:38 UTC
